---
title: "Final_ex2"
author: "Equipo"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
gauss.solver <- function(m, n, x)
{
n=n+1;
  x = unlist(strsplit(x,"[ ]"))


x <- as.numeric(gsub(",", " ", x))
x <- x[!is.na(x)]


M <- matrix(c(x),byrow=T,nrow=m,ncol=n)
M

M[1,] <- M[1,]/M[1,1]

i <- 2
while (i < m+1) {
 j <- i
 while (j < m+1) {
  M[j, ] <- M[j, ] - M[i-1, ] * M[j, i-1]
  j <- j+1
 }
 while (M[i,i] == 0) {
  M <- rbind(A[-i,],A[i,])
 }
 M[i,] <- M[i,]/M[i,i]
 i <- i+1
}
for (i in m:2){
 for (j in i:2-1) {
  M[j, ] <- M[j, ] - M[i, ] * M[j, i]
 }
}

M[,(m+1)]
}
```

```{r}

m <- readline(prompt="Number of equations: ")
n <- readline(prompt="Number of variables: ")
m <- as.numeric(m);
n <- as.numeric(n)


x= character(0)
for (i in 1:(m))
{
  y <- readline(prompt="Enter the equation separated by spaces i.e for 5x + y + 3z = -9 enter 5 1 3 -9 or for -5z = 0 enter 0 0 -5 0: ")
  x = paste(x,y, sep=" ")
}

gauss.solver (m,n,x)

```



#Ejemplo de una solución:

```{r}


x = "-3 2 -6 6 5 7 -5 6 1 4 -2 8"
m = 3
n = 3

gauss.solver (m,n,x)


```
